services:
  db:
    image: postgres
    volumes:
      - ./backend/data/db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: "pg_isready -U postgres"
      interval: 3s
      timeout: 3s
      retries: 5

  backend:
    build: ./backend
    command: >
      sh -c 'python3 manage.py makemigrations &&
             python3 manage.py migrate &&
             python3 import_csv.py &&
             python3 manage.py runserver 0.0.0.0:8000'
    volumes:
      - ./backend:/src
    ports:
      - "8000:8000"
    environment:
      POSTGRES_NAME: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@mail.com
      DJANGO_SUPERUSER_PASSWORD: admin1234
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://0.0.0.0:8000/ || exit 1"
      interval: 10s
      timeout: 3s
      retries: 5000
  
  frontend:
    build: ./frontend/project-frontend
    volumes: 
      - ./frontend/project-frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      backend:
        condition: service_healthy

